_format_version: "3.0"

plugins:
  - name: rate-limiting
    config:
      minute: 135
      policy: local
      limit_by: ip

services:
  - name: games-service
    url: http://games:4001
    routes:
      - name: games-routes
        paths:
          - /games
        strip_path: true

  - name: wallets-service
    url: http://wallets:4002
    routes:
      - name: wallets-routes
        paths:
          - /wallets
        strip_path: true
